stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cd /root/landing
    - git pull
    - npm install
    - echo "Compile complete."
  only:
    - main
    - merge_requests

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"
  only:
    - main
    - merge_requests

integrated-test-job:
  stage: test
  script:
    - echo "Running integrated tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"
  only:
    - main
    - merge_requests

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - cd /root/landing
    - npm install
    - npm run build
    - pm2 restart all
    - echo "Application successfully deployed."
  only:
    - main
    - merge_requests
